### ISSUE TITLE
i18next relevant repositories under joint organisation

### ISSUE THREAD

**Issue by jamuhl** [rbeere/i18next-jade-express-sample#1]
let's discuss this: https://github.com/jamuhl/i18next/issues/99

**Comment by chrisspiegl** [comment]
I would even go as far to add this repo into the 'sample' folder of the main 'i18next-node' repository! That would be ideal.

**Comment by jamuhl** [comment]
having done: https://github.com/i18next

so if anyone want to move his i18next related project contact me - so we could plan that.
